from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict

from .skill_base import Skill, SkillResult


class CodeSkill(Skill):
    name = "CodeSkill"
    description = "Creates or updates code files within the sandboxed workspace."

    def handle(self, instruction: str, context: Dict[str, Any]) -> SkillResult:
        workspace_root = Path(self.config.get("workspace_root", "./workspace")).resolve()
        workspace_root.mkdir(parents=True, exist_ok=True)

        pattern = re.compile(r"(?:create|make|write)\s+(?P<filename>[\w./-]+\.[a-zA-Z]{1,4})")
        match = pattern.search(instruction.lower())
        if not match:
            return SkillResult(
                status="failed",
                message="I could not identify which file to create. Please specify the filename.",
            )

        filename = match.group("filename")
        file_path = workspace_root / filename
        file_path.parent.mkdir(parents=True, exist_ok=True)

        content = self._infer_content(instruction, context)
        file_path.write_text(content, encoding="utf-8")

        return SkillResult(
            status="success",
            message=f"Created {file_path}",
            data={"file_path": str(file_path), "content": content},
        )

    def _infer_content(self, instruction: str, context: Dict[str, Any]) -> str:
        instruction_lower = instruction.lower()
        if "print" in instruction_lower and ".py" in instruction_lower:
            if "hello" in instruction_lower:
                return 'print("hello from envy")\n'
            return 'print("Envy executed the requested Python script.")\n'
        if ".md" in instruction_lower:
            return "# Generated by Envy\n\nThis file was created by the CodeSkill."
        if ".txt" in instruction_lower:
            return "Envy generated this text file based on your request."
        return "# Generated by Envy\n"
