from __future__ import annotations

import re
from pathlib import Path

from .base import SkillBase


class CodeSkill(SkillBase):
    name = "codeskill"
    description = "Creates or edits code files within the workspace."
    requires_confirmation = True
    is_envy_skill = True

    def handle(self, context):
        settings = context.config["skills"]["code"]
        root = Path(settings["workspace_root"]).resolve()
        filename = context.metadata.get("filename") or self._infer_filename(context.transcript)
        if not filename:
            raise ValueError("Could not determine filename from transcript.")
        target = root / filename
        if target.exists() and not settings.get("allow_overwrite", False):
            raise FileExistsError(f"{target} already exists and overwriting is disabled.")
        target.parent.mkdir(parents=True, exist_ok=True)

        content = context.metadata.get("content") or self._infer_content(context.transcript)
        target.write_text(content, encoding="utf-8")
        return f"Created {target} with {len(content.splitlines())} lines."

    def _infer_filename(self, transcript: str) -> str | None:
        match = re.search(r"(?:create|make)\s+([\w./-]+\.py)", transcript.lower())
        if match:
            return match.group(1)
        return None

    def _infer_content(self, transcript: str) -> str:
        if "print" in transcript.lower():
            return 'print("hello from envy")\n'
        return "# Generated by Envy CodeSkill\n"
