"""CodeSkill: handles code generation and file creation tasks."""

from __future__ import annotations

import re
from pathlib import Path

from .base import Skill, SkillContext, SkillResult


class CodeSkill(Skill):
    name = "CodeSkill"
    description = "Create or edit small code files within the workspace sandbox."
    requires_confirmation = False

    def execute(self, text: str, session_id: str, context: SkillContext) -> SkillResult:
        filename = self._extract_filename(text) or "generated.py"
        content = self._derive_content(text)
        target_path = self._resolve_path(filename, context)

        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")

        message = f"Created {target_path} with requested code."
        return SkillResult(
            status="ok",
            message=message,
            artifacts={"created_file": str(target_path)},
        )

    def _extract_filename(self, text: str) -> str | None:
        match = re.search(r"(?:create|make|write)\s+([\w./-]+\.py)", text.lower())
        if match:
            return match.group(1)
        return None

    def _derive_content(self, text: str) -> str:
        if "print" in text.lower():
            return 'print("hello from envy")\n'
        return (
            "# Generated by Envy CodeSkill\n"
            'print("Envy completed the requested code task.")\n'
        )

    def _resolve_path(self, filename: str, context: SkillContext) -> Path:
        base = Path.cwd()
        candidate = (base / filename).resolve()
        if not any(str(candidate).startswith(str((base / sandbox).resolve())) for sandbox in context.sandbox_paths):
            # Default to workspace sandbox root
            candidate = (base / context.sandbox_paths[0] / filename).resolve()
        return candidate


__all__ = ["CodeSkill"]

