"""
ResearchSkill: Research topics and generate summaries
"""
import os
from pathlib import Path
from typing import Dict, Any
from datetime import datetime

from skills.base_skill import BaseSkill
from services.config_loader import get_config


class ResearchSkill(BaseSkill):
    """Skill for researching topics"""
    
    def __init__(self):
        super().__init__("ResearchSkill")
        self.description = "Research topics and create summaries"
        self.actions = ['research']
        
        # Load settings
        output_dir = self.config.get('skills.research_skill.output_dir', 'workspace/research')
        base_dir = Path(__file__).parent.parent
        self.output_dir = base_dir / output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.max_sources = self.config.get('skills.research_skill.max_sources', 5)
        self.use_local_llm = self.config.get('skills.research_skill.use_local_llm', True)
        
        self.logger.info(f"ResearchSkill initialized (output: {self.output_dir})")
    
    def execute(self, action: str, command: str, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Execute research skill action"""
        
        if action == 'research':
            return self.research(command, parameters)
        else:
            return self.error_response(f"Unknown action: {action}")
    
    def research(self, command: str, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Research a topic"""
        self.logger.info(f"Researching: {command}")
        
        # Extract topic from command
        topic = self._extract_topic(command)
        
        if not topic:
            return self.error_response("Could not determine research topic")
        
        # Generate research summary
        summary = self._generate_summary(topic)
        
        # Save to file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_{topic.replace(' ', '_')[:30]}_{timestamp}.md"
        output_path = self.output_dir / filename
        
        try:
            with open(output_path, 'w') as f:
                f.write(f"# Research: {topic}\n\n")
                f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                f.write("## Summary\n\n")
                f.write(summary)
                f.write("\n\n---\n*Generated by Envy Personal Assistant*\n")
            
            self.logger.info(f"Research saved to: {output_path}")
            
            # Create spoken summary (shorter)
            spoken_summary = self._create_spoken_summary(topic, summary)
            
            return self.success_response(
                spoken_summary,
                data={
                    'topic': topic,
                    'file': str(output_path),
                    'summary': summary
                }
            )
            
        except Exception as e:
            self.logger.error(f"Failed to save research: {e}")
            return self.error_response(f"Failed to save research: {e}")
    
    def _extract_topic(self, command: str) -> str:
        """Extract research topic from command"""
        command_lower = command.lower()
        
        # Remove common prefixes
        prefixes = [
            'research',
            'look up',
            'find information about',
            'tell me about',
            'what is',
            'what are',
        ]
        
        topic = command_lower
        for prefix in prefixes:
            if topic.startswith(prefix):
                topic = topic[len(prefix):].strip()
                break
        
        return topic.strip()
    
    def _generate_summary(self, topic: str) -> str:
        """Generate research summary (using LLM or fallback)"""
        
        # Try to use LLM for better summaries
        try:
            from services.llm_adapter import LLMAdapter
            llm = LLMAdapter()
            
            prompt = f"Provide a brief, factual summary about: {topic}. Include 3-5 key points."
            summary = llm.generate(prompt)
            
            if summary and not summary.startswith('['):
                return summary
        except Exception as e:
            self.logger.warning(f"LLM generation failed: {e}")
        
        # Fallback: template-based summary
        return self._fallback_summary(topic)
    
    def _fallback_summary(self, topic: str) -> str:
        """Generate fallback summary when LLM not available"""
        return f"""
I would research "{topic}" for you, but I'm currently running without access to
external information sources or advanced language models.

Here's what I can tell you:

- **Topic**: {topic}
- **Note**: To get actual research results, please ensure:
  1. A local LLM is configured and loaded
  2. Or remote API access is enabled in config
  3. Or internet search capabilities are added

For now, I've created this placeholder document for you to fill in manually.

**Suggestions for research:**
- Use search engines to find reliable sources
- Look for academic papers or official documentation
- Check Wikipedia for basic overviews
- Verify information from multiple sources
"""
    
    def _create_spoken_summary(self, topic: str, full_summary: str) -> str:
        """Create shorter spoken version of summary"""
        
        # If LLM worked, create brief spoken version
        if "placeholder document" not in full_summary.lower():
            # Take first paragraph or sentence
            lines = full_summary.split('\n')
            first_para = lines[0] if lines else full_summary
            
            if len(first_para) > 200:
                first_para = first_para[:200] + "..."
            
            return f"I've researched {topic}. {first_para} The full summary has been saved to your research folder."
        else:
            return f"I've created a research template for {topic}, but I need an active language model to generate actual content. The file is ready for you to edit."


def main():
    """Test research skill standalone"""
    import logging
    logging.basicConfig(level=logging.INFO)
    
    skill = ResearchSkill()
    
    # Test research
    commands = [
        "research quantum computing",
        "look up artificial intelligence",
    ]
    
    for cmd in commands:
        print(f"\n--- Testing: {cmd} ---")
        result = skill.execute('research', cmd, {})
        print(f"Success: {result['success']}")
        print(f"Response: {result.get('response', result.get('error'))}")


if __name__ == "__main__":
    main()
