#!/bin/bash
# Cursor build log generator

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENVY_DIR="$SCRIPT_DIR/.."
LOG_FILE="$ENVY_DIR/cursor-build-log.txt"

echo "==========================================" > "$LOG_FILE"
echo "Envy Build Log - Generated by Cursor" >> "$LOG_FILE"
echo "Started: $(date)" >> "$LOG_FILE"
echo "==========================================" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

cd "$ENVY_DIR"

# Step 1: Installation test
echo "[STEP 1] Testing installation..." | tee -a "$LOG_FILE"
if [ -f "install_envy.sh" ]; then
    echo "Install script found" >> "$LOG_FILE"
    echo "PASS" | tee -a "$LOG_FILE"
else
    echo "FAIL: Install script missing" | tee -a "$LOG_FILE"
    exit 1
fi
echo "" >> "$LOG_FILE"

# Step 2: Run tests
echo "[STEP 2] Running acceptance tests..." | tee -a "$LOG_FILE"
if [ -f "scripts/run_tests.sh" ]; then
    bash scripts/run_tests.sh 2>&1 | tee -a "$LOG_FILE"
    TEST_EXIT=${PIPESTATUS[0]}
    if [ $TEST_EXIT -eq 0 ]; then
        echo "PASS" | tee -a "$LOG_FILE"
    else
        echo "FAIL: Some tests failed (exit code $TEST_EXIT)" | tee -a "$LOG_FILE"
    fi
else
    echo "FAIL: Test script missing" | tee -a "$LOG_FILE"
fi
echo "" >> "$LOG_FILE"

# Step 3: Performance report
echo "[STEP 3] Generating performance report..." | tee -a "$LOG_FILE"
if [ -f "scripts/perf-report-gen.sh" ]; then
    bash scripts/perf-report-gen.sh 2>&1 | tee -a "$LOG_FILE"
    echo "PASS" | tee -a "$LOG_FILE"
else
    echo "FAIL: Performance script missing" | tee -a "$LOG_FILE"
fi
echo "" >> "$LOG_FILE"

# Step 4: Package
echo "[STEP 4] Creating package..." | tee -a "$LOG_FILE"
if [ -f "scripts/package.sh" ]; then
    bash scripts/package.sh 2>&1 | tee -a "$LOG_FILE"
    if [ -f "../envy-ready.zip" ]; then
        echo "PASS: Package created" | tee -a "$LOG_FILE"
        ls -lh ../envy-ready.zip | tee -a "$LOG_FILE"
    else
        echo "FAIL: Package not created" | tee -a "$LOG_FILE"
    fi
else
    echo "FAIL: Package script missing" | tee -a "$LOG_FILE"
fi
echo "" >> "$LOG_FILE"

# Acceptance criteria check
echo "==========================================" >> "$LOG_FILE"
echo "Acceptance Criteria Check" >> "$LOG_FILE"
echo "==========================================" >> "$LOG_FILE"

PASS_COUNT=0
FAIL_COUNT=0

# Check 1: Wake word test
if grep -q "Wake word.*detected\|Wake word listener initialized" "$ENVY_DIR/artifacts/tests"/*.log 2>/dev/null; then
    echo "[✓] Wake word detection: PASS" >> "$LOG_FILE"
    ((PASS_COUNT++))
else
    echo "[✗] Wake word detection: FAIL" >> "$LOG_FILE"
    ((FAIL_COUNT++))
fi

# Check 2: CodeSkill test
if [ -f "$ENVY_DIR/workspace/test.py" ]; then
    if grep -q "hello" "$ENVY_DIR/workspace/test.py" 2>/dev/null; then
        echo "[✓] CodeSkill end-to-end: PASS" >> "$LOG_FILE"
        ((PASS_COUNT++))
    else
        echo "[✗] CodeSkill end-to-end: FAIL (file exists but content incorrect)" >> "$LOG_FILE"
        ((FAIL_COUNT++))
    fi
else
    echo "[✗] CodeSkill end-to-end: FAIL (file not created)" >> "$LOG_FILE"
    ((FAIL_COUNT++))
fi

# Check 3: TTS test
if [ -f "$ENVY_DIR/artifacts/tests/tts-output.wav" ] || grep -q "TTS.*completed\|TTS test passed" "$ENVY_DIR/artifacts/tests"/*.log 2>/dev/null; then
    echo "[✓] TTS synthesis: PASS" >> "$LOG_FILE"
    ((PASS_COUNT++))
else
    echo "[✗] TTS synthesis: FAIL" >> "$LOG_FILE"
    ((FAIL_COUNT++))
fi

# Check 4: Router/LLM test
if grep -q "Router.*result\|LLM.*response" "$ENVY_DIR/artifacts/tests"/*.log 2>/dev/null; then
    echo "[✓] Router/LLM fallback: PASS" >> "$LOG_FILE"
    ((PASS_COUNT++))
else
    echo "[✗] Router/LLM fallback: FAIL or SKIP" >> "$LOG_FILE"
    ((FAIL_COUNT++))
fi

# Check 5: Package exists
if [ -f "../envy-ready.zip" ]; then
    echo "[✓] envy-ready.zip exists: PASS" >> "$LOG_FILE"
    ((PASS_COUNT++))
    
    # Check package contents
    if unzip -l ../envy-ready.zip | grep -q "run_envy_local.sh\|install_envy.sh\|config/envy.yaml"; then
        echo "[✓] Package contents: PASS" >> "$LOG_FILE"
        ((PASS_COUNT++))
    else
        echo "[✗] Package contents: FAIL (missing required files)" >> "$LOG_FILE"
        ((FAIL_COUNT++))
    fi
else
    echo "[✗] envy-ready.zip exists: FAIL" >> "$LOG_FILE"
    ((FAIL_COUNT++))
fi

# Check 6: Test logs exist
if [ -d "$ENVY_DIR/artifacts/tests" ] && [ -n "$(ls -A $ENVY_DIR/artifacts/tests/*.log 2>/dev/null)" ]; then
    echo "[✓] Test logs exist: PASS" >> "$LOG_FILE"
    ((PASS_COUNT++))
else
    echo "[✗] Test logs exist: FAIL" >> "$LOG_FILE"
    ((FAIL_COUNT++))
fi

echo "" >> "$LOG_FILE"
echo "==========================================" >> "$LOG_FILE"
echo "Summary: $PASS_COUNT passed, $FAIL_COUNT failed" >> "$LOG_FILE"
echo "Completed: $(date)" >> "$LOG_FILE"
echo "==========================================" >> "$LOG_FILE"

# Final status
if [ $FAIL_COUNT -eq 0 ]; then
    echo "" >> "$LOG_FILE"
    echo "🎉 ALL ACCEPTANCE CRITERIA PASSED" >> "$LOG_FILE"
    cat "$LOG_FILE"
    exit 0
else
    echo "" >> "$LOG_FILE"
    echo "⚠️  SOME ACCEPTANCE CRITERIA FAILED" >> "$LOG_FILE"
    cat "$LOG_FILE"
    exit 1
fi
