"""
CodeSkill: creates or edits files as requested by the user.
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path
from typing import Optional

from .base import BaseSkill, SkillContext, SkillResult


class CodeSkill(BaseSkill):
    name = "code"
    description = "Create and modify source files."
    destructive = False

    def matches(self, transcript: str) -> bool:
        lowered = transcript.lower()
        return "create" in lowered and (".py" in lowered or "file" in lowered)

    async def execute(self, context: SkillContext) -> SkillResult:
        target_file = self._extract_filename(context.transcript)
        if not target_file:
            return SkillResult(success=False, message="Could not determine target filename.")

        workspace_root = Path(context.config.get("workspace_root", ".")).resolve()
        safe_dir = workspace_root
        safe_dir.mkdir(parents=True, exist_ok=True)
        destination = (safe_dir / target_file).resolve()

        if not str(destination).startswith(str(safe_dir)):
            return SkillResult(success=False, message="Invalid file path outside workspace.")

        body = self._infer_body(context.transcript)
        await asyncio.to_thread(self._write_file, destination, body)

        return SkillResult(
            success=True,
            message=f"Created {destination}",
            artifact_path=destination,
            metadata={"content": body},
        )

    def _extract_filename(self, transcript: str) -> Optional[str]:
        pattern = re.compile(r"(?:create|make)\s+(?:a\s+)?(?P<name>[\w./-]+\.\w+)", re.IGNORECASE)
        match = pattern.search(transcript)
        if match:
            return match.group("name")
        if "test.py" in transcript.lower():
            return "test.py"
        return None

    def _infer_body(self, transcript: str) -> str:
        if "print" in transcript.lower() and "hello" in transcript.lower():
            return 'print("hello from envy")\n'
        return "# Generated by Envy CodeSkill\n"

    def _write_file(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
