from __future__ import annotations

from pathlib import Path
import re
import textwrap
from datetime import datetime

from .base import BaseSkill, SkillRequest, SkillResponse
from ..services.common.config import EnvyConfig, PROJECT_ROOT
from ..services.common.logging import get_logger


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "research"


class ResearchSkill(BaseSkill):
    name = "research_skill"
    intents = ("research.summary",)

    def __init__(self, config: EnvyConfig) -> None:
        self.config = config
        self.logger = get_logger("ResearchSkill", config=config)
        self.output_dir = (PROJECT_ROOT / "workspace" / "research").resolve()

    def setup(self) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def handle(self, request: SkillRequest) -> SkillResponse:
        topic = request.parameters.get("topic") or self._infer_topic(request.transcript)
        filename = _slugify(topic) + ".md"
        target = self.output_dir / filename
        summary = self._generate_summary(topic)
        target.write_text(summary, encoding="utf-8")
        self.logger.info(f"Generated research summary at {target}")
        return SkillResponse(
            success=True,
            message=f"Research summary for '{topic}' saved to {target}",
            data={"path": str(target), "topic": topic},
        )

    def _infer_topic(self, transcript: str) -> str:
        match = re.search(r"research\s+(?P<topic>.+)", transcript, re.IGNORECASE)
        if match:
            return match.group("topic").strip()
        return "unspecified topic"

    def _generate_summary(self, topic: str) -> str:
        now = datetime.utcnow().isoformat()
        body = textwrap.dedent(
            f"""
            # Research Summary: {topic}

            Generated by Envy on {now} UTC.

            ## Overview

            This is an offline summary prepared by Envy's ResearchSkill. For a full
            deep-dive, enable the optional remote connectors in `config/envy.yaml`.

            ## Key Points

            - Envy captured a research request for: **{topic}**
            - No external network queries were performed in the default profile.
            - Populate this section with findings once remote sources are enabled.

            ## Next Steps

            1. Review the topic outline above.
            2. Enable opt-in connectors or add local knowledge sources in `workspace/research/`.
            3. Re-run the research skill for updated content.
            """
        ).strip()
        return body + "\n"


__all__ = ["ResearchSkill"]
