"""
ResearchSkill: summarises information about a topic.
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path

import textwrap

import aiohttp

from .base import BaseSkill, SkillContext, SkillResult


class ResearchSkill(BaseSkill):
    name = "research"
    description = "Gather and summarise information about a topic."
    destructive = False

    def matches(self, transcript: str) -> bool:
        return "research" in transcript.lower() or "look up" in transcript.lower()

    async def execute(self, context: SkillContext) -> SkillResult:
        topic = self._extract_topic(context.transcript)
        if not topic:
            return SkillResult(success=False, message="Could not determine research topic.")

        summary = await self._lookup(topic)
        artifacts_dir = context.artifacts_dir / "research"
        artifacts_dir.mkdir(parents=True, exist_ok=True)
        filename = artifacts_dir / f"{self._slugify(topic)}.txt"

        await asyncio.to_thread(filename.write_text, summary, "utf-8")

        return SkillResult(
            success=True,
            message=f"Research summary saved to {filename}",
            artifact_path=filename,
            metadata={"topic": topic},
        )

    def _extract_topic(self, transcript: str) -> str:
        match = re.search(r"(?:research|look up)\s+(?P<topic>.+)", transcript, re.IGNORECASE)
        if match:
            return match.group("topic").strip()
        return transcript.strip()

    async def _lookup(self, topic: str) -> str:
        query = topic.strip()
        fallback_summary = textwrap.dedent(
            f"""
            Research Summary for: {query}

            - Overview: This is a placeholder summary generated locally. Configure remote research providers in
              config/envy.yaml to enrich this output with live data.
            - Actionable Next Steps:
              * Review locally stored knowledge base or documentation related to "{query}".
              * Enable optional remote providers (e.g., Wikipedia API) by editing the configuration.

            Generated by Envy ResearchSkill.
            """
        ).strip()

        try:
            async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=10)) as session:
                async with session.get(
                    "https://duckduckgo.com/html/",
                    params={"q": query},
                    headers={"User-Agent": "EnvyAssistant/1.0"},
                ) as response:
                    if response.status == 200:
                        text = await response.text()
                        snippet = self._extract_snippet(text)
                        if snippet:
                            return textwrap.dedent(
                                f"""
                                Research Summary for: {query}

                                - Overview: {snippet}
                                - Sources: DuckDuckGo search (HTML lite)

                                Generated by Envy ResearchSkill.
                                """
                            ).strip()
        except Exception:
            pass

        return fallback_summary

    def _extract_snippet(self, html: str) -> str:
        match = re.search(r"<a[^>]+class=\"result__a\"[^>]*>(.*?)</a>", html, re.IGNORECASE | re.DOTALL)
        if not match:
            return ""
        snippet = re.sub("<.*?>", "", match.group(1))
        return snippet.strip()

    def _slugify(self, text: str) -> str:
        slug = re.sub(r"[^a-z0-9]+", "-", text.lower())
        return slug.strip("-") or "topic"
