from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Optional

from .base import Skill, SkillContext, SkillResult

LOGGER = logging.getLogger(__name__)


class CodeSkill(Skill):
    name = "code"
    description = "Create or modify source files safely inside the workspace."

    def can_handle(self, command: str) -> bool:
        lowered = command.lower()
        return "create" in lowered or "code" in lowered or ".py" in lowered

    def execute(self, command: str, context: SkillContext) -> SkillResult:
        LOGGER.info("CodeSkill handling command: %s", command)

        filename = self._extract_filename(command) or "generated.py"
        safe_name = Path(filename).name  # prevent path traversal
        target = context.workspace_dir / safe_name
        target.parent.mkdir(parents=True, exist_ok=True)

        if "print" in command.lower() and "hello" in command.lower():
            contents = 'print("hello from envy")\n'
        else:
            contents = (
                "# Generated by Envy CodeSkill\n"
                "def main():\n"
                '    print("Envy acknowledges your command.")\n'
                "\n"
                "if __name__ == \"__main__\":\n"
                "    main()\n"
            )

        target.write_text(contents, encoding="utf-8")
        LOGGER.info("Wrote file %s", target)

        return SkillResult(
            handled=True,
            response=f"Created {safe_name} with the requested changes.",
            artifacts=[target],
        )

    @staticmethod
    def _extract_filename(command: str) -> Optional[str]:
        match = re.search(r"([\w\-]+\.\w+)", command)
        if match:
            return match.group(1)
        if "python" in command.lower():
            return "script.py"
        return None
